query TourneyCountry($country:String) {
  tournaments(query:{
    perPage: 50
    filter: {
      countryCode: $country
    }
  }){
    nodes {
      name
      slug
      url(relative:false)
      images {
        url
      }
      numAttendees
      events (limit:2){
        name
        slug
        videogame {
          displayName
        }
      }
    }
  }
}